vich_uploader:
    db_driver: orm

    mappings:
        map_object_images:
            uri_prefix: /images/map_object
            upload_destination: "%kernel.project_dir%/public/images/map_object"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        event_images:
            uri_prefix: /images/event
            upload_destination: "%kernel.project_dir%/public/images/event"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        main_window_media:
            uri_prefix: /media/main_window
            upload_destination: "%kernel.project_dir%/public/media/main_window"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer